apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: foundations
spec:
  releaseName: openebs
  serviceAccountName: flux-admin
  chart:
    spec:
      chart: openebs
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: foundations
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    engines:
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      analytics:
        enabled: false
    lvm-localpv:
      analytics:
        enabled: false
    zfs-localpv:
      analytics:
        enabled: false
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: foundations
spec:
  interval: 1h0m0s
  url: https://openebs.github.io/openebs
