apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-admin-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-admin-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: flux-admin
    namespace: foundations
roleRef:
  kind: ClusterRole
  name: flux-admin-clusterrole
  apiGroup: rbac.authorization.k8s.io
